use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet};
use std::fs::OpenOptions;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, RwLock};
use std::time::{SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};

use crate::{
    MemoryKind, MemoryLifecycle, MemoryPrincipal, MemoryQuery, MemoryRecord, MemoryRelation,
    MemorySearchDiagnostics, MemorySearchHit, MemorySearchResult, VerificationStatus,
};

static TEMP_COUNTER: AtomicU64 = AtomicU64::new(0);

#[derive(Debug, thiserror::Error)]
pub enum MemoryError {
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
    #[error("serialization: {0}")]
    Serde(#[from] serde_json::Error),
    #[error("memory must retain at least one source artifact")]
    MissingSource,
    #[error("idempotency key {0:?} was already used for different content")]
    IdempotencyConflict(String),
    #[error("principal {principal:?} is not authorized for memory {record_id}")]
    AccessDenied {
        principal: String,
        record_id: String,
    },
    #[error("federated stores contain different records with id {0}")]
    FederationConflict(String),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RecordOutcome {
    Created,
    AlreadyPresent,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CompactionReport {
    pub records: usize,
    pub bytes: usize,
}

#[derive(Debug, Serialize, Deserialize)]
struct CompactedSnapshot {
    schema: String,
    fingerprint: Vec<RecordFingerprint>,
    records: Vec<MemoryRecord>,
    digest: String,
}

#[derive(Debug, Clone)]
pub struct MemoryStore {
    root: PathBuf,
    peers: Arc<Vec<PathBuf>>,
    cache: Arc<RwLock<Option<CachedIndex>>>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
struct RecordFingerprint {
    name: String,
    len: u64,
    modified_nanos: u128,
}

#[derive(Debug, Clone)]
struct CachedIndex {
    fingerprint: Vec<RecordFingerprint>,
    index: Arc<MemoryIndex>,
}

#[derive(Debug)]
struct MemoryIndex {
    records: Vec<MemoryRecord>,
    loaded_from_compaction: bool,
    text: HashMap<String, BTreeSet<usize>>,
    symbols: HashMap<String, BTreeSet<usize>>,
    kinds: HashMap<MemoryKind, BTreeSet<usize>>,
}

impl MemoryStore {
    pub fn open(root: impl Into<PathBuf>) -> Self {
        Self {
            root: root.into(),
            peers: Arc::new(Vec::new()),
            cache: Arc::new(RwLock::new(None)),
        }
    }

    pub fn open_federated<I, P>(root: impl Into<PathBuf>, peers: I) -> Self
    where
        I: IntoIterator<Item = P>,
        P: Into<PathBuf>,
    {
        Self {
            root: root.into(),
            peers: Arc::new(peers.into_iter().map(Into::into).collect()),
            cache: Arc::new(RwLock::new(None)),
        }
    }

    pub fn root(&self) -> &Path {
        &self.root
    }

    pub fn roots(&self) -> Vec<PathBuf> {
        std::iter::once(self.root.clone())
            .chain(self.peers.iter().cloned())
            .collect()
    }

    pub fn record(&self, record: &MemoryRecord) -> Result<RecordOutcome, MemoryError> {
        self.record_inner(record, false)
    }

    pub fn record_as(
        &self,
        record: &MemoryRecord,
        principal: &MemoryPrincipal,
    ) -> Result<RecordOutcome, MemoryError> {
        if !principal.can_access(record) {
            return Err(MemoryError::AccessDenied {
                principal: principal.id.clone(),
                record_id: record.id.clone(),
            });
        }
        self.record_inner(record, false)
    }

    /// Record an observation whose occurrence/recording timestamps were
    /// generated by the caller at request time. An identical retry may arrive
    /// later, so those two fields are compared against the first persisted
    /// values while every source-grounded field remains conflict-checked.
    pub fn record_with_generated_timestamps(
        &self,
        record: &MemoryRecord,
    ) -> Result<RecordOutcome, MemoryError> {
        self.record_inner(record, true)
    }

    pub fn record_with_generated_timestamps_as(
        &self,
        record: &MemoryRecord,
        principal: &MemoryPrincipal,
    ) -> Result<RecordOutcome, MemoryError> {
        if !principal.can_access(record) {
            return Err(MemoryError::AccessDenied {
                principal: principal.id.clone(),
                record_id: record.id.clone(),
            });
        }
        self.record_inner(record, true)
    }

    fn record_inner(
        &self,
        record: &MemoryRecord,
        generated_timestamps: bool,
    ) -> Result<RecordOutcome, MemoryError> {
        if record.sources.is_empty() {
            return Err(MemoryError::MissingSource);
        }
        let records = self.root.join("records");
        std::fs::create_dir_all(&records)?;
        let target = records.join(format!("{}.json", record.id));
        if target.exists() {
            return compare_existing(&target, record, generated_timestamps);
        }

        let bytes = serde_json::to_vec_pretty(record)?;
        let nonce = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos();
        let counter = TEMP_COUNTER.fetch_add(1, Ordering::Relaxed);
        let tmp = records.join(format!(
            ".{}.{}.{}.{}.tmp",
            record.id,
            std::process::id(),
            nonce,
            counter
        ));
        {
            let mut file = OpenOptions::new().create_new(true).write(true).open(&tmp)?;
            file.write_all(&bytes)?;
            file.sync_all()?;
        }
        match std::fs::rename(&tmp, &target) {
            Ok(()) => {
                self.invalidate_cache();
                Ok(RecordOutcome::Created)
            }
            Err(_error) if target.exists() => {
                let _ = std::fs::remove_file(&tmp);
                compare_existing(&target, record, generated_timestamps)
            }
            Err(error) => {
                let _ = std::fs::remove_file(&tmp);
                Err(error.into())
            }
        }
    }

    pub fn all(&self) -> Result<Vec<MemoryRecord>, MemoryError> {
        Ok(self.index()?.records.clone())
    }

    pub fn all_authorized(
        &self,
        principal: &MemoryPrincipal,
    ) -> Result<Vec<MemoryRecord>, MemoryError> {
        Ok(self
            .index()?
            .records
            .iter()
            .filter(|record| principal.can_access(record))
            .cloned()
            .collect())
    }

    pub fn search(&self, query: &MemoryQuery) -> Result<Vec<MemorySearchHit>, MemoryError> {
        self.search_authorized(query, &MemoryPrincipal::operator())
    }

    pub fn search_authorized(
        &self,
        query: &MemoryQuery,
        principal: &MemoryPrincipal,
    ) -> Result<Vec<MemorySearchHit>, MemoryError> {
        Ok(self
            .search_with_diagnostics_authorized(query, principal)?
            .hits)
    }

    pub fn search_with_diagnostics(
        &self,
        query: &MemoryQuery,
    ) -> Result<MemorySearchResult, MemoryError> {
        self.search_with_diagnostics_authorized(query, &MemoryPrincipal::operator())
    }

    pub fn search_with_diagnostics_authorized(
        &self,
        query: &MemoryQuery,
        principal: &MemoryPrincipal,
    ) -> Result<MemorySearchResult, MemoryError> {
        let index = self.index()?;
        let query_tokens = tokens(&query.text);
        let symbol = query
            .symbol
            .as_deref()
            .map(str::trim)
            .filter(|s| !s.is_empty())
            .map(str::to_lowercase);
        let mut hits = Vec::new();
        let candidates = index
            .candidates(&query_tokens, symbol.as_deref(), &query.kinds)
            .into_iter()
            .filter(|record_index| principal.can_access(&index.records[*record_index]))
            .collect::<BTreeSet<_>>();
        let visible_records = index
            .records
            .iter()
            .filter(|record| principal.can_access(record))
            .collect::<Vec<_>>();
        let visible_superseded = visible_records
            .iter()
            .flat_map(|record| &record.links)
            .filter(|link| link.relation == MemoryRelation::Supersedes)
            .map(|link| link.target.as_str())
            .collect::<HashSet<_>>();
        let diagnostics = MemorySearchDiagnostics {
            total_records: visible_records.len(),
            candidate_records: candidates.len(),
            loaded_from_compaction: index.loaded_from_compaction,
        };

        for record_index in candidates {
            let record = &index.records[record_index];
            if !query.kinds.is_empty() && !query.kinds.contains(&record.kind) {
                continue;
            }
            if !query.include_superseded
                && (matches!(
                    record.lifecycle,
                    MemoryLifecycle::Superseded | MemoryLifecycle::Retracted
                ) || visible_superseded.contains(record.id.as_str()))
            {
                continue;
            }

            let mut score = 0.0;
            let mut matched_by = Vec::new();
            if let Some(symbol) = &symbol {
                let matched = record.affected_symbols.iter().any(|anchor| {
                    [
                        anchor.node_id.as_str(),
                        anchor.label.as_str(),
                        anchor.source_file.as_str(),
                    ]
                    .iter()
                    .any(|value| value.to_lowercase().contains(symbol))
                }) || record.path_changes.iter().any(|change| {
                    change
                        .old_path
                        .iter()
                        .chain(change.new_path.iter())
                        .any(|path| path.to_lowercase().contains(symbol))
                }) || record.symbol_changes.iter().any(|change| {
                    [&change.old, &change.new].iter().any(|anchor| {
                        [
                            anchor.node_id.as_str(),
                            anchor.label.as_str(),
                            anchor.source_file.as_str(),
                        ]
                        .iter()
                        .any(|value| value.to_lowercase().contains(symbol))
                    })
                });
                if !matched {
                    continue;
                }
                score += 4.0;
                matched_by.push("symbol".to_string());
            }

            if !query_tokens.is_empty() {
                let title = tokens(&record.title);
                let summary = tokens(&record.summary);
                let source = tokens(
                    &record
                        .sources
                        .iter()
                        .map(|s| format!("{} {}", s.kind, s.uri))
                        .collect::<Vec<_>>()
                        .join(" "),
                );
                let mut text_score = 0.0;
                for token in &query_tokens {
                    if title.contains(token) {
                        text_score += 2.0;
                    }
                    if summary.contains(token) {
                        text_score += 1.0;
                    }
                    if source.contains(token) {
                        text_score += 0.4;
                    }
                }
                if text_score == 0.0 {
                    continue;
                }
                score += text_score;
                matched_by.push("text".to_string());
            }

            if query_tokens.is_empty() && symbol.is_none() {
                score += 1.0;
                matched_by.push("recent".to_string());
            }
            score += f64::from(record.confidence.clamp(0.0, 1.0));
            score += match record.verification.status {
                VerificationStatus::Passed | VerificationStatus::Failed => 0.5,
                VerificationStatus::Partial => 0.25,
                VerificationStatus::Unknown => 0.0,
            };
            hits.push(MemorySearchHit {
                record: record.clone(),
                score,
                matched_by,
            });
        }
        hits.sort_by(|a, b| {
            b.score
                .total_cmp(&a.score)
                .then_with(|| b.record.occurred_at.cmp(&a.record.occurred_at))
                .then_with(|| a.record.id.cmp(&b.record.id))
        });
        hits.truncate(if query.limit == 0 { 20 } else { query.limit });
        Ok(MemorySearchResult { hits, diagnostics })
    }

    /// Persist a verified compact snapshot of the primary store. Immutable
    /// record files remain the audit source of truth; a matching fingerprint
    /// lets a later process load one sequential file instead of thousands.
    pub fn compact(&self) -> Result<CompactionReport, MemoryError> {
        let (files, fingerprint) = record_files(&self.root)?;
        let mut records = read_records(&files)?;
        sort_records(&mut records);
        let digest = records_digest(&records)?;
        let snapshot = CompactedSnapshot {
            schema: "synaptic.memory-compact/v1".into(),
            fingerprint,
            records,
            digest,
        };
        let bytes = serde_json::to_vec(&snapshot)?;
        std::fs::create_dir_all(&self.root)?;
        synaptic_core::fsio::write_atomic(&self.root.join("index.compact-v1.json"), &bytes)?;
        self.invalidate_cache();
        Ok(CompactionReport {
            records: snapshot.records.len(),
            bytes: bytes.len(),
        })
    }

    fn invalidate_cache(&self) {
        *self
            .cache
            .write()
            .unwrap_or_else(|error| error.into_inner()) = None;
    }

    fn index(&self) -> Result<Arc<MemoryIndex>, MemoryError> {
        let mut fingerprint = Vec::new();
        let mut states = Vec::new();
        for root in self.roots() {
            let (files, root_fingerprint) = record_files(&root)?;
            fingerprint.extend(root_fingerprint.iter().map(|entry| RecordFingerprint {
                name: format!("{}::{}", root.to_string_lossy(), entry.name),
                len: entry.len,
                modified_nanos: entry.modified_nanos,
            }));
            states.push((root, files, root_fingerprint));
        }
        fingerprint.sort_by(|a, b| a.name.cmp(&b.name));
        if let Some(cached) = self
            .cache
            .read()
            .unwrap_or_else(|error| error.into_inner())
            .as_ref()
            .filter(|cached| cached.fingerprint == fingerprint)
        {
            return Ok(cached.index.clone());
        }

        let mut records_by_id = BTreeMap::<String, MemoryRecord>::new();
        let mut loaded_from_compaction = true;
        let mut had_records = false;
        for (root, files, root_fingerprint) in states {
            had_records |= !files.is_empty();
            let (root_records, compacted) = match load_compacted(&root, &root_fingerprint)? {
                Some(records) => (records, true),
                None => (read_records(&files)?, false),
            };
            if !files.is_empty() && !compacted {
                loaded_from_compaction = false;
            }
            for record in root_records {
                match records_by_id.get(&record.id) {
                    Some(existing) if existing != &record => {
                        return Err(MemoryError::FederationConflict(record.id));
                    }
                    Some(_) => {}
                    None => {
                        records_by_id.insert(record.id.clone(), record);
                    }
                }
            }
        }
        let mut records = records_by_id.into_values().collect::<Vec<_>>();
        sort_records(&mut records);
        let index = Arc::new(MemoryIndex::build(
            records,
            had_records && loaded_from_compaction,
        ));
        *self
            .cache
            .write()
            .unwrap_or_else(|error| error.into_inner()) = Some(CachedIndex {
            fingerprint,
            index: index.clone(),
        });
        Ok(index)
    }
}

impl MemoryIndex {
    fn build(records: Vec<MemoryRecord>, loaded_from_compaction: bool) -> Self {
        let mut text = HashMap::<String, BTreeSet<usize>>::new();
        let mut symbols = HashMap::<String, BTreeSet<usize>>::new();
        let mut kinds = HashMap::<MemoryKind, BTreeSet<usize>>::new();
        for (index, record) in records.iter().enumerate() {
            kinds.entry(record.kind).or_default().insert(index);
            let source_text = record
                .sources
                .iter()
                .map(|source| format!("{} {}", source.kind, source.uri))
                .collect::<Vec<_>>()
                .join(" ");
            for token in tokens(&format!(
                "{} {} {source_text}",
                record.title, record.summary
            )) {
                text.entry(token).or_default().insert(index);
            }
            for value in record
                .affected_symbols
                .iter()
                .flat_map(|anchor| {
                    [
                        anchor.node_id.as_str(),
                        anchor.label.as_str(),
                        anchor.source_file.as_str(),
                    ]
                })
                .chain(record.path_changes.iter().flat_map(|change| {
                    change
                        .old_path
                        .iter()
                        .chain(change.new_path.iter())
                        .map(String::as_str)
                }))
                .chain(record.symbol_changes.iter().flat_map(|change| {
                    [&change.old, &change.new].into_iter().flat_map(|anchor| {
                        [
                            anchor.node_id.as_str(),
                            anchor.label.as_str(),
                            anchor.source_file.as_str(),
                        ]
                    })
                }))
            {
                for token in tokens(value) {
                    symbols.entry(token).or_default().insert(index);
                }
            }
        }
        Self {
            records,
            loaded_from_compaction,
            text,
            symbols,
            kinds,
        }
    }

    fn candidates(
        &self,
        query_tokens: &HashSet<String>,
        symbol: Option<&str>,
        kinds: &[MemoryKind],
    ) -> BTreeSet<usize> {
        let all = || (0..self.records.len()).collect::<BTreeSet<_>>();
        let text_candidates = (!query_tokens.is_empty()).then(|| {
            query_tokens
                .iter()
                .filter_map(|token| self.text.get(token))
                .flatten()
                .copied()
                .collect::<BTreeSet<_>>()
        });
        let symbol_tokens = symbol.map(tokens).unwrap_or_default();
        let symbol_candidates = symbol.map(|_| {
            if symbol_tokens.is_empty() {
                all()
            } else {
                symbol_tokens
                    .iter()
                    .filter_map(|token| self.symbols.get(token))
                    .flatten()
                    .copied()
                    .collect::<BTreeSet<_>>()
            }
        });
        let kind_candidates = (!kinds.is_empty()).then(|| {
            kinds
                .iter()
                .filter_map(|kind| self.kinds.get(kind))
                .flatten()
                .copied()
                .collect::<BTreeSet<_>>()
        });
        [text_candidates, symbol_candidates, kind_candidates]
            .into_iter()
            .flatten()
            .reduce(|left, right| left.intersection(&right).copied().collect())
            .unwrap_or_else(all)
    }
}

fn record_files(root: &Path) -> Result<(Vec<PathBuf>, Vec<RecordFingerprint>), std::io::Error> {
    let directory = root.join("records");
    let entries = match std::fs::read_dir(directory) {
        Ok(entries) => entries,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            return Ok((Vec::new(), Vec::new()))
        }
        Err(error) => return Err(error),
    };
    let mut files = Vec::new();
    for entry in entries {
        let entry = entry?;
        if entry
            .path()
            .extension()
            .and_then(|extension| extension.to_str())
            == Some("json")
        {
            files.push(entry.path());
        }
    }
    files.sort();
    let fingerprint = files
        .iter()
        .map(|path| {
            let metadata = std::fs::metadata(path)?;
            let modified_nanos = metadata
                .modified()
                .ok()
                .and_then(|modified| modified.duration_since(UNIX_EPOCH).ok())
                .map(|duration| duration.as_nanos())
                .unwrap_or(0);
            Ok(RecordFingerprint {
                name: path
                    .file_name()
                    .unwrap_or_default()
                    .to_string_lossy()
                    .into_owned(),
                len: metadata.len(),
                modified_nanos,
            })
        })
        .collect::<Result<Vec<_>, std::io::Error>>()?;
    Ok((files, fingerprint))
}

fn read_records(files: &[PathBuf]) -> Result<Vec<MemoryRecord>, MemoryError> {
    files
        .iter()
        .map(|path| Ok(serde_json::from_slice(&std::fs::read(path)?)?))
        .collect()
}

fn sort_records(records: &mut [MemoryRecord]) {
    records.sort_by(|a, b| {
        a.occurred_at
            .cmp(&b.occurred_at)
            .then_with(|| a.id.cmp(&b.id))
    });
}

fn records_digest(records: &[MemoryRecord]) -> Result<String, serde_json::Error> {
    Ok(blake3::hash(&serde_json::to_vec(records)?)
        .to_hex()
        .to_string())
}

fn load_compacted(
    root: &Path,
    fingerprint: &[RecordFingerprint],
) -> Result<Option<Vec<MemoryRecord>>, MemoryError> {
    let bytes = match std::fs::read(root.join("index.compact-v1.json")) {
        Ok(bytes) => bytes,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(error) => return Err(error.into()),
    };
    let Ok(snapshot) = serde_json::from_slice::<CompactedSnapshot>(&bytes) else {
        return Ok(None);
    };
    if snapshot.schema != "synaptic.memory-compact/v1" || snapshot.fingerprint != fingerprint {
        return Ok(None);
    }
    if records_digest(&snapshot.records)? != snapshot.digest {
        return Ok(None);
    }
    Ok(Some(snapshot.records))
}

fn compare_existing(
    target: &Path,
    record: &MemoryRecord,
    generated_timestamps: bool,
) -> Result<RecordOutcome, MemoryError> {
    let existing: MemoryRecord = serde_json::from_slice(&std::fs::read(target)?)?;
    let mut candidate = record.clone();
    // The version identifies the serialization shape, not the observation's
    // source-grounded identity. Defaulted fields make an old record readable;
    // an otherwise identical retry after an upgrade must remain idempotent.
    candidate.version = existing.version;
    let equivalent = if generated_timestamps {
        candidate.occurred_at = existing.occurred_at;
        candidate.recorded_at = existing.recorded_at;
        existing == candidate
    } else {
        existing == candidate
    };
    if equivalent {
        Ok(RecordOutcome::AlreadyPresent)
    } else {
        Err(MemoryError::IdempotencyConflict(
            record.idempotency_key.clone(),
        ))
    }
}

fn tokens(text: &str) -> HashSet<String> {
    text.split(|ch: char| !ch.is_alphanumeric())
        .filter(|token| token.chars().count() >= 2)
        .map(str::to_lowercase)
        .collect()
}
