use std::collections::HashSet;

use synaptic_core::{Edge, Node, NodeId};
use tree_sitter::{Node as TsNode, Parser};

use crate::config::{LanguageConfig, TypeRefStyle};
use crate::paths::{file_node_id, file_stem};
use crate::result::{ExtractionResult, ImportRecord, RawCall};

mod core;
mod cpp;
mod csharp;
mod ecmascript;
mod java;
mod kotlin;
mod php;
mod python;
mod scala;
mod swift;

/// Recursion guard for both passes — bounds stack depth on pathologically nested
/// input.
const MAX_DEPTH: usize = 2000;

/// Comment markers that flag design rationale.
const RATIONALE_MARKERS: &[&str] = &[
    "NOTE",
    "IMPORTANT",
    "HACK",
    "WHY",
    "RATIONALE",
    "TODO",
    "FIXME",
];
/// Line-comment tokens scanned for those markers — covers Python (`#`),
/// C-family (`//`) and SQL/Lua (`--`).
const COMMENT_TOKENS: &[&str] = &["#", "//", "--"];

/// Strip a Python string literal's surrounding quotes + whitespace (the optional
/// `r`/`f`/`b` prefix is left as-is; only the `"`/`'` quote chars are stripped).
fn strip_py_quotes(s: &str) -> String {
    s.trim()
        .trim_matches(|c| c == '"' || c == '\'')
        .trim()
        .to_string()
}

/// The docstring of `node`'s body: its first child, if an `expression_statement`
/// wrapping a string > 20 chars → `(text, 1-based line)`.
/// Used for module (`node` = root), class, and function bodies.
fn first_docstring(node: TsNode<'_>, source: &[u8]) -> Option<(String, usize)> {
    let mut cursor = node.walk();
    let first = node.children(&mut cursor).next()?;
    if first.kind() != "expression_statement" {
        return None;
    }
    let mut inner = first.walk();
    for sub in first.children(&mut inner) {
        if matches!(sub.kind(), "string" | "concatenated_string") {
            let text = strip_py_quotes(sub.utf8_text(source).unwrap_or(""));
            if text.chars().count() > 20 {
                return Some((text, first.start_position().row + 1));
            }
        }
    }
    None
}

/// True for files whose module docstring is boilerplate, not rationale
/// (codegen/protobuf/Alembic/Django).
fn is_autogenerated_python(source: &[u8]) -> bool {
    let head = String::from_utf8_lossy(&source[..source.len().min(2048)]);
    head.contains("DO NOT EDIT")
        || head.contains("@generated")
        || head.contains("Generated by the protocol buffer")
        || (head.contains("down_revision") && head.contains("def upgrade("))
        || (head.contains("class Migration(migrations.Migration)") && head.contains("operations"))
}

/// Extract one file's content using `cfg`. Two passes: a structural DFS, then an
/// intra-file call pass over collected function bodies.
pub fn extract_with_config(path: &str, source: &[u8], cfg: &LanguageConfig) -> ExtractionResult {
    let mut parser = Parser::new();
    parser
        .set_language(&(cfg.language)())
        .expect("load tree-sitter language");
    let Some(tree) = parser.parse(source, None) else {
        return ExtractionResult::default();
    };

    let mut ex = Extractor {
        cfg,
        source,
        path: path.to_string(),
        nodes: Vec::new(),
        edges: Vec::new(),
        raw_calls: Vec::new(),
        imports: Vec::new(),
        seen: HashSet::new(),
        function_bodies: Vec::new(),
        interface_names: HashSet::new(),
    };

    let file_nid = file_node_id(path);
    let file_label = std::path::Path::new(path)
        .file_name()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_else(|| path.to_string());
    ex.add_node(file_nid.clone(), file_label, 1);

    let stem = file_stem(path);
    ex.pre_scan(tree.root_node());
    ex.walk(tree.root_node(), &file_nid, None, &stem, 0);
    ex.run_call_pass();
    ex.scan_rationale_comments(&file_nid, &stem);
    // Module docstring (Python only; class/function docstrings are handled inline
    // during the walk so there is no second parse). Skips auto-generated files.
    if matches!(cfg.type_ref_style, Some(TypeRefStyle::Python)) && !is_autogenerated_python(source)
    {
        if let Some((doc, line)) = first_docstring(tree.root_node(), source) {
            ex.add_rationale(doc, line, file_nid.clone(), &stem);
        }
    }

    ExtractionResult {
        nodes: ex.nodes,
        edges: ex.edges,
        raw_calls: ex.raw_calls,
        imports: ex.imports,
    }
}

struct Extractor<'cfg, 'src, 'tree> {
    cfg: &'cfg LanguageConfig,
    source: &'src [u8],
    path: String,
    nodes: Vec<Node>,
    edges: Vec<Edge>,
    raw_calls: Vec<RawCall>,
    imports: Vec<ImportRecord>,
    seen: HashSet<NodeId>,
    function_bodies: Vec<(NodeId, TsNode<'tree>)>,
    /// In-file interface/protocol names from a pre-scan, so heritage
    /// classification (C#/Swift) can tell interfaces from base classes. Empty
    /// unless the language's heritage style uses it.
    interface_names: HashSet<String>,
}

/// True for the C# `IFoo` interface-naming convention: a leading `I` followed by
/// an uppercase letter (`IDisposable` yes, `Item` no).
fn is_csharp_interface_name(name: &str) -> bool {
    let mut chars = name.chars();
    chars.next() == Some('I') && chars.next().is_some_and(|c| c.is_uppercase())
}

/// Well-known TS built-in type containers/utilities skipped as type references.
/// Primitives are `predefined_type` nodes and never reach here.
fn is_ts_type_noise(name: &str) -> bool {
    matches!(
        name,
        "Array"
            | "ReadonlyArray"
            | "Promise"
            | "Map"
            | "Set"
            | "WeakMap"
            | "WeakSet"
            | "Record"
            | "Readonly"
            | "Partial"
            | "Required"
            | "Pick"
            | "Omit"
            | "Exclude"
            | "Extract"
            | "NonNullable"
            | "Parameters"
            | "ReturnType"
            | "Awaited"
            | "Date"
            | "RegExp"
            | "Error"
    )
}

/// Module stem = last path component of a JS/TS import specifier, with any known
/// JS/TS extension stripped. The cross-file symbol-resolution key
/// (`./util` → `util`, `react` → `react`, `@scope/pkg` → `pkg`, `../a/b.js` → `b`).
fn module_stem(spec: &str) -> String {
    let last = spec.rsplit('/').next().unwrap_or(spec);
    for ext in [".d.ts", ".tsx", ".ts", ".jsx", ".js", ".mjs", ".cjs"] {
        if let Some(base) = last.strip_suffix(ext) {
            return base.to_string();
        }
    }
    last.to_string()
}

/// Resolve a Python relative import (`from .pkg.mod import …`) to the path string
/// whose `make_id` matches the imported file's node id. The relative branch
/// counts leading dots, climbs `dots-1` parents from the importing file's
/// directory, then appends `module/path.py` (or `__init__.py`).
fn resolve_relative_import(file_path: &str, raw: &str) -> String {
    let dots = raw.len() - raw.trim_start_matches('.').len();
    let module = raw.trim_start_matches('.');
    let mut base = std::path::Path::new(file_path)
        .parent()
        .map(|p| p.to_path_buf())
        .unwrap_or_default();
    for _ in 0..dots.saturating_sub(1) {
        base = base.parent().map(|p| p.to_path_buf()).unwrap_or_default();
    }
    let rel = if module.is_empty() {
        "__init__.py".to_string()
    } else {
        format!("{}.py", module.replace('.', "/"))
    };
    base.join(rel).to_string_lossy().into_owned()
}

#[cfg(all(test, feature = "lang-python"))]
mod tests;
