//! Cypher export for Neo4j / FalkorDB. Values in
//! string position are escaped; values in identifier position (node label / rel
//! type) are allowlisted to `[A-Za-z0-9_]` (Cypher can't escape those).

use std::fs;
use std::io;
use std::path::Path;

use synaptic_graph::KnowledgeGraph;

use crate::common::{confidence_str, file_type_str};

/// Escape a string for a single-quoted Cypher literal (drops control bytes;
/// escapes `\`, `'`, newlines, CRs so a payload can't break the statement line).
fn escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        // Drop C0 controls (except tab/newline/cr, which we escape) and DEL:
        // a raw newline would let a payload break the `;`-terminated statement.
        if (ch < ' ' && !matches!(ch, '\t' | '\n' | '\r')) || ch == '\u{7f}' {
            continue;
        }
        match ch {
            '\\' => out.push_str("\\\\"),
            '\'' => out.push_str("\\'"),
            '\t' => out.push_str("\\t"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            _ => out.push(ch),
        }
    }
    out
}

/// Sanitise a value used in identifier position (label / relationship type):
/// strip to `[A-Za-z0-9_]` and require a leading letter, else `fallback`.
fn ident(raw: &str, fallback: &str) -> String {
    let cleaned: String = raw
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '_')
        .collect();
    match cleaned.chars().next() {
        Some(c) if c.is_ascii_alphabetic() => cleaned,
        _ => fallback.to_string(),
    }
}

/// The individual idempotent statements (node merges first, then edge merges),
/// **without** a trailing `;`. `to_cypher_string` terminates each with `;` for
/// the import-script file; the live push runs each through a session / `GRAPH.QUERY`.
///
/// Both forms are **idempotent on re-run**: the `MERGE` key is the id alone and
/// `label`/`confidence` are applied with `SET`, so re-importing after a label or
/// confidence change updates the node/edge in place instead of creating a
/// duplicate (the old form inlined them in the `MERGE` pattern, which created
/// duplicates when they changed).
///
/// `rich` additionally writes `source_file` + `community` onto nodes (for a live
/// DB push, via `SET n += $props`); the static `graph.cypher` script stays lean
/// (id/label only).
pub fn cypher_statements(kg: &KnowledgeGraph, rich: bool) -> Vec<String> {
    let gd = kg.to_graph_data();
    let mut out = Vec::with_capacity(gd.nodes.len() + gd.links.len());
    for n in &gd.nodes {
        let ftype = ident(&capitalize(&file_type_str(&n.file_type)), "Entity");
        let mut sets = format!("n.label = '{}'", escape(&n.label));
        if rich {
            if !n.source_file.is_empty() {
                sets.push_str(&format!(", n.source_file = '{}'", escape(&n.source_file)));
            }
            if let Some(c) = n.community {
                sets.push_str(&format!(", n.community = {c}"));
            }
            if let Some(k) = n.kind() {
                sets.push_str(&format!(", n.kind = '{}'", escape(k.as_str())));
            }
            if let Some(v) = n.visibility() {
                sets.push_str(&format!(", n.visibility = '{}'", escape(v.as_str())));
            }
            if let Some(loc) = n.loc() {
                sets.push_str(&format!(", n.loc = {loc}"));
            }
        }
        out.push(format!(
            "MERGE (n:{ftype} {{id: '{}'}}) SET {sets}",
            escape(&n.id.0)
        ));
    }
    for e in &gd.links {
        let rel = ident(&e.relation.to_uppercase(), "RELATES_TO");
        out.push(format!(
            "MATCH (a {{id: '{}'}}), (b {{id: '{}'}}) MERGE (a)-[r:{rel}]->(b) SET r.confidence = '{}'",
            escape(&e.source.0),
            escape(&e.target.0),
            escape(&confidence_str(&e.confidence)),
        ));
    }
    out
}

/// Render the graph as a Cypher import script (`;`-terminated statements).
pub fn to_cypher_string(kg: &KnowledgeGraph) -> String {
    let mut lines = vec![
        "// Neo4j Cypher import - generated by Synaptic".to_string(),
        String::new(),
    ];
    for stmt in cypher_statements(kg, false) {
        lines.push(format!("{stmt};"));
    }
    lines.join("\n")
}

fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        Some(f) => f.to_uppercase().chain(c).collect(),
        None => String::new(),
    }
}

/// Write `graph.cypher`.
pub fn to_cypher(kg: &KnowledgeGraph, path: &Path) -> io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, to_cypher_string(kg))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tests_support::{kg_with_label, sample_kg};
    use serde_json::Map;
    use synaptic_core::{Confidence, Edge, FileType, GraphData, Node, NodeId};

    #[test]
    fn cypher_emits_idempotent_merge_nodes_and_rels() {
        let c = to_cypher_string(&sample_kg());
        // id is the MERGE key; label/confidence go in SET so a re-run after a
        // change updates in place instead of duplicating.
        assert!(
            c.contains("MERGE (n:Code {id: 'a'}) SET n.label = 'A';"),
            "got: {c}"
        );
        assert!(
            c.contains("MERGE (a)-[r:CALLS]->(b) SET r.confidence = 'INFERRED';")
                || c.contains("MERGE (a)-[r:CALLS]->(b) SET r.confidence = 'EXTRACTED';"),
            "got: {c}"
        );
    }

    #[test]
    fn cypher_escapes_quotes_and_allowlists_idents() {
        // String escaping: a label with a quote/newline must be escaped.
        let c = to_cypher_string(&kg_with_label("evil", "a'b\nc"));
        assert!(c.contains("SET n.label = 'a\\'b\\nc'"), "got: {c}");
        assert!(!c.contains("'a'b\nc'"));

        // Identifier allowlisting: a hostile relation/file_type can't inject a
        // label or relationship type (Cypher can't escape those positions).
        let gd = GraphData {
            directed: false,
            multigraph: false,
            graph: Map::new(),
            nodes: vec![stub_node("a", "A"), stub_node("b", "B")],
            links: vec![Edge {
                source: NodeId("a".into()),
                target: NodeId("b".into()),
                relation: "calls()-[:HACK]-(".into(),
                confidence: Confidence::Extracted,
                source_file: "x".into(),
                source_location: None,
                confidence_score: None,
                weight: 1.0,
                context: None,
                cross_repo: false,
                extra: Map::new(),
            }],
            hyperedges: vec![],
            built_at_commit: None,
        };
        let c = to_cypher_string(&synaptic_graph::KnowledgeGraph::from_graph_data(gd));
        // Punctuation stripped to a bare allowlisted relationship type.
        assert!(c.contains("-[r:CALLSHACK]->"), "ident not allowlisted: {c}");
        assert!(!c.contains("HACK]-("), "injection survived: {c}");
    }

    #[test]
    fn rich_statements_add_community_and_source_file() {
        // The live-push (`rich`) form carries source_file + community; the static
        // script (default) does not.
        let stmts = cypher_statements(&sample_kg(), true);
        let node_a = stmts.iter().find(|s| s.contains("{id: 'a'}")).unwrap();
        assert!(node_a.contains("n.source_file = 'a.py'"), "got: {node_a}");
        assert!(node_a.contains("n.community = "), "got: {node_a}");
        // Lean form omits both.
        let lean = cypher_statements(&sample_kg(), false);
        assert!(lean.iter().all(|s| !s.contains("source_file")));
    }

    fn stub_node(id: &str, label: &str) -> Node {
        Node {
            id: NodeId(id.into()),
            label: label.into(),
            file_type: FileType::Code,
            source_file: "x".into(),
            source_location: None,
            community: None,
            repo: None,
            extra: Map::new(),
        }
    }
}
